id = "asciidoc"
name = "AsciiDoc"
version = "0.5.6"
schema_version = 1
authors = ["Dunya Kirkali <dunyakirkali@gmail.com>"]
description = "Support for AsciiDoc syntax"
repository = "https://github.com/dunyakirkali/zed-asciidoc"
snippets = "./snippets/asciidoc.json"

[grammars.asciidoc_inline]
repository = "https://github.com/cathaysia/tree-sitter-asciidoc"
commit = "c0b6adb497cb707b3a13c3d846aac1f54a1a1b5e"
path = "tree-sitter-asciidoc_inline"

[grammars.asciidoc]
repository = "https://github.com/cathaysia/tree-sitter-asciidoc"
commit = "c0b6adb497cb707b3a13c3d846aac1f54a1a1b5e"
path = "tree-sitter-asciidoc"
